//
// Created by AnDTN on 2/15/2023.
//

#ifndef STUDENT_MANAGEMENT_SYSTEM_EX3_INCLUDES_LOGOUT_H_
#define STUDENT_MANAGEMENT_SYSTEM_EX3_INCLUDES_LOGOUT_H_
void logoutSystem();
#endif //STUDENT_MANAGEMENT_SYSTEM_EX3_INCLUDES_LOGOUT_H_
