//
// Created by AnDTN on 2/13/2023.
//

#ifndef STUDENT_MANAGEMENT_SYSTEM_EX3_SRC_SUBJECT_FUNCTION_H_
#define STUDENT_MANAGEMENT_SYSTEM_EX3_SRC_SUBJECT_FUNCTION_H_

class SubjectFunction {

};

#endif //STUDENT_MANAGEMENT_SYSTEM_EX3_SRC_SUBJECT_FUNCTION_H_
